### ISSUE TITLE
Delete implausible data from previous years

### ISSUE THREAD

**Issue by daria-sl** [globe-swiss/phaenonet-functions#51]
The following implausible data should be deleted in the database, because it is implausible:

- Hasel (PhaenoNet): 2015 und 2011, Allgemeine Blattentfaltung, alles ab Juni rauslöschen
- Hasel (PhaenoNet): 2013, Allgemeine Blüte, alles ab Juni rauslöschen

**Comment by pgoellnitz** [comment]
removed 5 observations:
 -> 989_2015_HS_BEA(2015-10-01 00:00:00+00:00)
 -> 989_2015_HS_BLA(2015-09-23 00:00:00+00:00)
 -> 108_2011_HS_BEA(2011-07-27 00:00:00+00:00)
 -> 691_2013_HS_BLA(2013-09-30 00:00:00+00:00)
 -> 718_2013_HS_BLA(2013-11-15 00:00:00+00:00)
